In [1]:
from load import load_data, GraphPreprocess
dataset = "reddit"
graph, _ = load_data(dataset, small_trainingset=1.0, pretransform=GraphPreprocess(True, True))

/home/lxw/miniconda3/envs/pyg/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/lxw/miniconda3/envs/pyg/lib/python3.8/site-packages/torch_geometric/data/dataset.py:209: UserWarning: The `pre_transform` argument differs from the one used in the pre-processed version of this dataset. If you want to make use of another pre-processing technique, make sure to delete 'dataset/Reddit/processed' first
  warnings.warn(


In [2]:
graph.num_nodes, graph.num_edges

(232965, 114615892)

In [3]:
graph.edge_index

tensor([[     0,      0,      0,  ..., 232964, 232964, 232964],
        [   242,    249,    524,  ..., 231806, 232594, 232634]])

In [4]:
import torch
idx = torch.load("/home/lxw/work/VirtualNodeGraph_v2/cluster_data/reddit_clutser_metis_16.pt")
idx.shape

torch.Size([16, 232965])

In [5]:
edge_index = graph.edge_index

In [6]:
vn_indices = torch.nonzero(idx.T)
vn_indices

tensor([[     0,      2],
        [     1,      7],
        [     2,     12],
        ...,
        [232962,     14],
        [232963,      0],
        [232964,      2]])

In [7]:
vn_indices

tensor([[     0,      2],
        [     1,      7],
        [     2,     12],
        ...,
        [232962,     14],
        [232963,      0],
        [232964,      2]])

In [8]:
edge_index

tensor([[     0,      0,      0,  ..., 232964, 232964, 232964],
        [   242,    249,    524,  ..., 231806, 232594, 232634]])

In [19]:
edge_index_tmp = edge_index[:, :10000] 

In [10]:
edge_index_tmp

tensor([[    0,     0,     0,  ...,    25,    25,    25],
        [  242,   249,   524,  ..., 88710, 95748, 97067]])

In [11]:
def f(x, *y):
    return vn_indices[x][1]

In [21]:
part_edge_inde

tensor([[15, 15, 15,  ..., 13, 13, 13],
        [ 5,  2,  5,  ...,  0, 10,  0]])

tensor([15, 15, 15,  ..., 13, 13, 13])

In [1]:
import argparse

import torch
import torch.nn.functional as F

import torch_geometric.transforms as T
from torch_geometric.nn import GCNConv, SAGEConv

from ogb.nodeproppred import PygNodePropPredDataset, Evaluator

In [3]:
import argparse

import torch
import torch.nn.functional as F

import torch_geometric.transforms as T
from torch_geometric.nn import GCNConv, SAGEConv

from ogb.nodeproppred import PygNodePropPredDataset, Evaluator

In [4]:
dataset = PygNodePropPredDataset(root='dataset',
        name='ogbn-proteins', transform=T.ToSparseTensor(attr='edge_attr'))
data = dataset[0]

In [5]:
data.x = data.adj_t.mean(dim=1)
data.adj_t.set_value_(None)

SparseTensor(row=tensor([     0,      0,      0,  ..., 132533, 132533, 132533]),
             col=tensor([     1,      2,      3,  ...,  98734, 102639, 132517]),
             size=(132534, 132534), nnz=79122504, density=0.45%)

In [6]:
data.x.shape

torch.Size([132534, 8])

In [7]:
data.adj_t

SparseTensor(row=tensor([     0,      0,      0,  ..., 132533, 132533, 132533]),
             col=tensor([     1,      2,      3,  ...,  98734, 102639, 132517]),
             size=(132534, 132534), nnz=79122504, density=0.45%)

In [8]:
data.num_nodes

132534

In [9]:
hasattr(data, "edge_index")

True

In [10]:
data.edge_index

In [17]:
data

Data(num_nodes=132534, node_species=[132534, 1], y=[132534, 112], adj_t=[132534, 132534, nnz=79122504], x=[132534, 8])

In [12]:
data.y.shape[1]

112

In [13]:
data.y.max()

tensor(1)

In [14]:
data.y

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        ...,
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0],
        [0, 0, 0,  ..., 0, 0, 0]])

In [19]:
data.y.dim()


2